version: "3.7"
services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    restart: always
    volumes:
      - data-base:/var/lib/mysql
    environment:
      MYSQL_DDB_NAME: $MYSQL_DDB_NAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - network
  nginx:
    image: nginx:inception
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - website:/var/www/html
    networks:
      network:
        aliases:
          - "cmarouf.42.fr"
  wordpress:
    image: wordpress:inception
    container_name: wordpress
    depends_on: 
     - mariadb
    restart: always
    volumes:
      - website:/var/www/html
    environment:
      MYSQL_DDB_NAME: $MYSQL_DDB_NAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      DB_HOST: $DB_HOST
      WP_ADMIN_USER: $WP_ADMIN_USER
      WP_ADMIN_PASSWORD: $WP_ADMIN_PASSWORD
      WP_ADMIN_EMAIL: $WP_ADMIN_EMAIL
      WP_USER: $WP_USER
      WP_USER_PASSWORD: $WP_USER_PASSWORD
      WP_USER_EMAIL: $WP_USER_EMAIL
    networks:
      - network

networks:
  network:


volumes:
  website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/$USER/data/wordpress"
  data-base:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/$USER/data/db"

