version: "3.7"
services:
  mariadb:
    image: mariadb_inception
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mysql-log:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: %

volumes:
  mysql-log:
